#!/bin/bash

set -e

GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m'

LARAVEL_DIR="/var/www/crm-kw/LARAVEL CRM V2"
REACT_DIR="/var/www/crm-kw/REACT CRM V2"

echo -e "${YELLOW}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${YELLOW}   🚀 CRM Deploy - مركز مطمئنة${NC}"
echo -e "${YELLOW}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"

# ── 1. Git Pull ──────────────────────────────
echo -e "\n${GREEN}[1/7] سحب آخر التعديلات...${NC}"
cd "/var/www/crm-kw"

# lockfiles get regenerated by composer/npm install a few steps below anyway — discard any
# local drift in them now so a stale lockfile never silently aborts the whole deploy at `set -e`.
git checkout -- "LARAVEL CRM V2/composer.lock" "REACT CRM V2/package-lock.json" 2>/dev/null || true
git pull origin main

# ── 2. Laravel ──────────────────────────────
echo -e "\n${GREEN}[2/7] تحديث Laravel...${NC}"
cd "$LARAVEL_DIR"

composer install --no-interaction --prefer-dist --optimize-autoloader --no-dev

php artisan migrate --force
php artisan storage:link --force 2>/dev/null || true
php artisan config:clear
php artisan cache:clear
php artisan route:clear
php artisan view:clear
php artisan config:cache
php artisan route:cache
php artisan view:cache

# ── 3. React Build ───────────────────────────
echo -e "\n${GREEN}[3/7] بناء React...${NC}"
cd "$REACT_DIR"

npm ci --silent
npm run build

# تأكد أن البناء نجح
if [ -f "$REACT_DIR/dist/index.html" ]; then
    BUILD_DIR="$REACT_DIR/dist"
elif [ -f "$REACT_DIR/build/index.html" ]; then
    BUILD_DIR="$REACT_DIR/build"
else
    echo -e "${RED}  ✗ فشل بناء React — index.html غير موجود!${NC}"
    exit 1
fi
echo -e "${GREEN}  ✓ React build ناجح ($(du -sh "$BUILD_DIR" | cut -f1))${NC}"

# ── 4. Permissions ───────────────────────────
echo -e "\n${GREEN}[4/7] ضبط الصلاحيات...${NC}"
chown -R www-data:www-data "$LARAVEL_DIR/storage"
chown -R www-data:www-data "$LARAVEL_DIR/bootstrap/cache"
chmod -R 775 "$LARAVEL_DIR/storage"
chmod -R 775 "$LARAVEL_DIR/bootstrap/cache"

# ── 5. Restart Services ──────────────────────
echo -e "\n${GREEN}[5/7] إعادة تشغيل الخدمات...${NC}"

# امسح كاش nginx إن وجد
if [ -d /var/cache/nginx ]; then
    rm -rf /var/cache/nginx/* 2>/dev/null || true
fi

systemctl reload nginx
systemctl restart php8.2-fpm


# تأكد أن index.html محدث (امسح كاش PHP OPcache)
php -r "opcache_reset();" 2>/dev/null || true

# ── 6. Queue Worker ──────────────────────────
echo -e "\n${GREEN}[6/7] إعادة تشغيل Queue Worker...${NC}"
cd "$LARAVEL_DIR"

# أوقف أي queue:work قديم
php artisan queue:restart

# شغّل queue worker عبر supervisor لو متوفر، وإلا شغّله مباشرة
if command -v supervisorctl &> /dev/null; then
    # جرّب الأسماء المعروفة وأوقف عند أول نجاح
    supervisorctl restart laravel-worker-v2:* 2>/dev/null || \
    supervisorctl restart laravel-worker:* 2>/dev/null || \
    supervisorctl restart crm-worker:* 2>/dev/null || \
    supervisorctl restart all 2>/dev/null || true
    echo -e "${GREEN}  ✓ Supervisor أعاد تشغيل الـ worker${NC}"
else
    # تشغيل مباشر في الخلفية (fallback)
    pkill -f "artisan queue:work" 2>/dev/null || true
    sleep 1
    nohup php artisan queue:work --tries=3 --timeout=120 --sleep=3 >> /var/log/crm-queue.log 2>&1 &
    echo -e "${GREEN}  ✓ Queue worker يعمل في الخلفية (PID: $!)${NC}"
fi

# ── 7. Reverb (WebSocket) ─────────────────────
echo -e "\n${GREEN}[7/7] إعادة تشغيل Reverb (WebSocket)...${NC}"
cd "$LARAVEL_DIR"

# Reverb يجب أن يبقى شغّال دايماً كـ persistent process (زي queue worker بالضبط) — لازم
# supervisor group اسمه laravel-reverb معرّف يدوياً مرة وحدة على السيرفر (راجع توثيق النشر).
if command -v supervisorctl &> /dev/null && supervisorctl status laravel-reverb:* &> /dev/null; then
    supervisorctl restart laravel-reverb:*
    echo -e "${GREEN}  ✓ Supervisor أعاد تشغيل Reverb${NC}"
else
    echo -e "${YELLOW}  ⚠ لم يتم العثور على مجموعة supervisor باسم laravel-reverb — تحديثات الكود لن تنعكس على WebSocket حتى تعيد تشغيله يدوياً${NC}"
fi

echo -e "\n${YELLOW}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${GREEN}   ✅ تم النشر بنجاح!${NC}"
echo -e "${YELLOW}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}\n"

echo -e "${YELLOW}تذكير: تأكد من وجود هذا السطر في crontab (crontab -e):${NC}"
echo -e "  * * * * * cd \"$LARAVEL_DIR\" && php artisan schedule:run >> /dev/null 2>&1\n"
